name: continuous integration

on: push

jobs:
  build-artifact:
    name: Build
    runs-on: ubuntu-18.04

    steps:
    - name: checkout repository
      uses: actions/checkout@master
      with:
        submodules: recursive
    - name: setup environment
      run: >-
        sudo bash setup.bash
    - name: setup docker
      run: >-
        sudo bash setup-docker.bash
    - name: extract
      run: >-
        bash extract.bash
    - name: config and build
      run: >-
        sudo bash build-switch-docker.bash
    - name: package stdlib
      run: >-
        bash package-stdlib.bash
    - name: upload stdlib artifact
      uses: actions/upload-artifact@master
      with:
        name: python27-stdlib
        path: python27.zip
    - name: upload prefix artifact
      uses: actions/upload-artifact@master
      with:
        name: python27-switch
        path: python27-switch.tar.gz

  create-release:
    needs: [build-artifact]
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download stdlib artifact
      uses: actions/download-artifact@v1
      with:
        name: python27-stdlib

    - name: Download prefix artifact
      uses: actions/download-artifact@v1
      with:
        name: python27-switch

    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: "${{ contains(github.ref, '-rc') }}"
        files: |
          python27-stdlib/*
          python27-switch/*
